### ISSUE TITLE
Some installation skipped but accidently downloaded nethack-3.6.7-x86_64-2.txz to /boot/extra/

### ISSUE THREAD

**Issue by cloudiful** [ich777/un-get#17] opened 2024-10-31 15:09 UTC
Hi, When I was trying to install unibilium, I encountered a weird issue.

```bash
➜  extra pwd
/boot/extra

➜  extra ls
glibc-2.40-x86_64-5.txz   lua-lpeg-1.1.0-x86_64-4cf.txz  msgpack-c-6.1.0-x86_64-1cf.txz  openssl-solibs-3.4.0-x86_64-1.txz  
tree-sitter-0.24.3-x86_64-1.txz libvterm-0_3_3-x86_64-1cf.txz  luv-1.48.0-x86_64-3cf.txz      neovim-0.10.1-x86_64-1cf.txz    
rust-1.82.0-x86_64-1.txz   zsh-5.9-x86_64-1.txz

➜  extra un-get search unibilium
Please wait, performing search...
Found the following package(s) for your search 'unibilium' in repositories:
unibilium-92d929f

➜  extra un-get install unibilium
The following package(s) will be installed: unibilium
Are you sure? [y/N] y

     0K ........ ........ ......                             100% 1009K=1.4s

Package  already installed, skipping!

➜  extra ls
glibc-2.40-x86_64-5.txz        luv-1.48.0-x86_64-3cf.txz       nethack-3.6.7-x86_64-2.txz         tree-sitter-0.24.3-x86_64-1.txz
libvterm-0_3_3-x86_64-1cf.txz  msgpack-c-6.1.0-x86_64-1cf.txz  openssl-solibs-3.4.0-x86_64-1.txz  zsh-5.9-x86_64-1.txz
lua-lpeg-1.1.0-x86_64-4cf.txz  neovim-0.10.1-x86_64-1cf.txz    rust-1.82.0-x86_64-1.txz
➜  extra nvim
nvim: error while loading shared libraries: libunibilium.so.4: cannot open shared object file: No such file or directory
```

I also encounter this issue while installing libvterm, the installation is skipped and the nethack pkg is downloaded, so I manually download libvterm-0_3_3-x86_64-1cf.txz and put it in extra dir instead.

Here is some extra info:

OS: Unraid 6.12.13.

```bash
➜  extra uname -a
Linux inet 6.1.106-Unraid (...) 2024 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux

➜  extra cat /etc/os-release
NAME=Slackware
VERSION="15.0"
ID=slackware
VERSION_ID=15.0
PRETTY_NAME="Slackware 15.0 x86_64 (post 15.0 -current)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:15.0"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=current

➜  extra un-get -v
Written by Christoph Hummer for unRAID.
Version: 0.26
Date: 2024-04-09
Dual-licensed under MIT or UNLICENSE.
```

**Comment by cloudiful** [comment] 2024-10-31 15:35
I add some echo, and found that the LAT_V is null.

Installing unibilium

```bash
➜  un-get un-get install unibilium
The following package(s) will be installed: unibilium
Are you sure? [y/N] y

     0K ........ ........ ......                             100% 1.18M=1.2s

p: unibilium
LAT_V:
PACKAGE: /tmp/un-get/filelist-current:-rw-r--r-- ./y/nethack-3.6.7-x86_64-2.txz
TOP_URL: /y/nethack-3.6.7-x86_64-2.txz
REPO_LINE: 1
REPO: current
PACKAGE_NAME:
Package  already installed, skipping!
```
I got nothing while running this command

```bash
grep -R -H -i -w "unibilium-[0-9]\+" /tmp/un-get/
```

But I can see some result with this:

```bash
➜  un-get grep -R -H -i -w "unibilium" /tmp/un-get/
/tmp/un-get/checksums-conraid:f6df9afaf62d4cafcbf626a1300698b2  ./unibilium/README
/tmp/un-get/checksums-conraid:1a949a63676314d19a643efeecda6293  ./unibilium/unibilium-92d929f-x86_64-2cf.lst
/tmp/un-get/checksums-conraid:bfe27a0f3cf6838a24dff70541d6f85a  ./unibilium/unibilium-92d929f-x86_64-2cf.meta
/tmp/un-get/checksums-conraid:089d28649436752d8e9ed85ccd16a319  ./unibilium/unibilium-92d929f-x86_64-2cf.txt
/tmp/un-get/checksums-conraid:32ef87c79b047abb170223415fa9f6fa  ./unibilium/unibilium-92d929f-x86_64-2cf.txz
/tmp/un-get/checksums-conraid:2505bd7336bcced8eef7e07ee879a639  ./unibilium/unibilium-92d929f-x86_64-2cf.txz.asc
/tmp/un-get/checksums-conraid:c04c513208c9d8d4c0d969cd1ede27e4  ./unibilium/unibilium-92d929f-x86_64-2cf.txz.md5
/tmp/un-get/filelist-conraid:drwxr-xr-x 2 1000 100     4096 2024-04-27 15:55 ./unibilium
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100      432 2024-04-27 15:55 ./unibilium/README
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100     6036 2021-06-03 10:40 ./unibilium/unibilium-92d929f-x86_64-2cf.lst
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100      563 2023-12-27 11:05 ./unibilium/unibilium-92d929f-x86_64-2cf.meta
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100      323 2021-06-03 10:40 ./unibilium/unibilium-92d929f-x86_64-2cf.txt
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100   127092 2021-06-03 10:39 ./unibilium/unibilium-92d929f-x86_64-2cf.txz
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100      508 2021-06-03 10:40 ./unibilium/unibilium-92d929f-x86_64-2cf.txz.asc
/tmp/un-get/filelist-conraid:-rw-r--r-- 1 1000 100       67 2021-06-03 10:40 ./unibilium/unibilium-92d929f-x86_64-2cf.txz.md5
```
I found that the issue is that 92d929f is not all [0-9], so change it from [0-9] to [0-9a-zA-Z] works.

**Comment by ich777** [comment] 2024-11-01 09:18
Thanks for the PR, really much appreciated! I've merged it already and generated a new release.

If the issue is solved please close this issue.

**Closed** 2024-11-01 10:53 UTC
