### ISSUE TITLE
un-get fails to install tgz packages

### ISSUE THREAD

**Issue by nearcatch** [ich777/un-get#8] opened 2022-11-09 17:49 UTC
![image](https://user-images.githubusercontent.com/692914/200902748-826aa7ef-d362-4de3-9a97-6cdaf309a3fe.png)
![image](https://user-images.githubusercontent.com/692914/200902784-df0e0346-7a1a-472e-a6aa-2f5e3ceabedd.png)

**Comment by ich777** [comment] 2022-11-09 18:03
Can you give me a little more information on this, is this a third party repository?

Over here it installs p7zip-17.04 just fine:
![grafik](https://user-images.githubusercontent.com/28066518/200906124-08671d63-315e-49e1-902c-d7997af4e45d.png)

**Comment by ich777** [comment] 2022-11-09 20:03
It should always grab the latest version from a package, regardless which version and from where it‘s available.
Please give me a few days, I will look into this but I can‘t reproduce this on my server, maybe it‘s because of the last repo you have in your sources.
Will take a look at that repo too.

**Comment by ich777** [comment] 2022-11-10 08:56
@nearcatch thank you for the report, I've released `v0.19` or `2022.11.10` respectively and the issue with not installing packages and also with not installing latest packages should be fixed with this release.

In your case please also run `un-get remove p7zip unrar` first to remove the packages from the package list and also remove the packages from the `/boot/extra` folder if they are still in there.
After you've upgraded please run `un-get install p7zip unrar` and it should look something like this:
![grafik](https://user-images.githubusercontent.com/28066518/201045217-368d26b9-bffd-438e-b8b9-5d13b5044082.png)


If you experience any further issues feel free to re-open up this issue again or create a new issue.

**Closed by ich777** 2022-11-10 08:56 UTC

**Comment by nearcatch** [comment] 2022-11-11 06:41
worked perfectly, thanks
